# Generated by Django 5.2.7 on 2025-10-10 23:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome ou título do evento.', max_length=200)),
                ('tipo_evento', models.CharField(choices=[('seminario', 'Seminário'), ('palestra', 'Palestra'), ('congresso', 'Congresso'), ('workshop', 'Workshop'), ('outro', 'Outro')], help_text='Tipo do evento (ex: seminário, palestra).', max_length=50)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início do evento.')),
                ('data_fim', models.DateTimeField(help_text='Data e hora de término do evento.')),
                ('local', models.CharField(help_text='Local onde o evento ocorrerá.', max_length=255)),
                ('quantidade_participantes', models.PositiveIntegerField(default=0, help_text='Número máximo de participantes permitidos.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato do usuário.', max_length=15, null=True)),
                ('instituicao_ensino', models.CharField(blank=True, help_text='Instituição de ensino (obrigatório para alunos e professores).', max_length=255, null=True)),
                ('perfil', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='aluno', help_text='Perfil do usuário no sistema.', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('inscricao', models.OneToOneField(help_text='A inscrição que deu origem a este certificado.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sgea_app.inscricao')),
                ('codigo_validacao', models.CharField(help_text='Código único para validação do certificado.', max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificado',
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='sgea_app.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(help_text='Organizador responsável pelo evento.', limit_choices_to={'perfil': 'organizador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_inscritos', through='sgea_app.Inscricao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('usuario', 'evento')},
        ),
    ]
