# Generated by Django 6.0 on 2025-12-05 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagem promocional do evento (apenas .jpg, .png, .jpeg).', null=True, upload_to='eventos/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quantidade_participantes',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de participantes permitidos.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
