# Generated by Django 6.0 on 2025-12-06 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgea_app', '0002_evento_banner_alter_evento_quantidade_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='professor_responsavel',
            field=models.ForeignKey(help_text='Professor responsável pelo evento.', limit_choices_to={'perfil': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
