# Generated by Django 6.0 on 2025-12-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgea_app', '0003_evento_professor_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='presenca',
            field=models.BooleanField(default=False, help_text='Indica se o participante esteve presente no evento.'),
        ),
    ]
