# Generated by Django 6.0 on 2025-12-06 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgea_app', '0004_inscricao_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('cadastro_usuario', 'Cadastro de Usuário'), ('criacao_evento', 'Criação de Evento'), ('edicao_evento', 'Edição de Evento'), ('exclusao_evento', 'Exclusão de Evento'), ('inscricao', 'Inscrição em Evento'), ('cancelamento', 'Cancelamento de Inscrição'), ('presenca', 'Marcação de Presença'), ('certificado', 'Geração de Certificado'), ('login', 'Login')], max_length=50)),
                ('detalhes', models.TextField(blank=True, help_text='Descrição detalhada da ação (ex: nome do evento, usuário afetado).', null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou a ação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'log_auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
