# Generated by Django 6.0 on 2025-12-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgea_app', '0005_logauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('criacao_usuario', 'Criação de Usuário'), ('login', 'Login no Sistema'), ('evento_cadastro', 'Cadastro de Evento'), ('evento_edicao', 'Alteração de Evento'), ('evento_exclusao', 'Exclusão de Evento'), ('evento_consulta_api', 'Consulta API Eventos'), ('inscricao', 'Inscrição em Evento'), ('certificado_geracao', 'Geração de Certificado'), ('certificado_consulta', 'Consulta de Certificado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que realizou a ação (pode ser null se for anônimo/sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='logauditoria',
            table=None,
        ),
    ]
